[package]
name = "flog"
version = "0.1.0"
authors = ["Patrik Lundgren <patrik.lundgren.95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "3.0.5", features = ["derive"] }
anyhow = "1.0"
rust-crypto = "0.2.3"
inotify = "0.10.0"

[lib]
name = "flib"
path = "src/lib.rs"


[[bin]]
name = "flogctl"
path = "src/flogctl.rs"

[[bin]]
name = "flogd"
path = "src/flogd.rs"
